<?php
function ajax_reader_init(){
  drupal_add_js('misc/jquery.form.js');
  drupal_add_library('system', 'drupal.ajax');
}

/**
 * Implements hook menu()
 */
function ajax_reader_menu(){
//A menu callback is required when using ajax outside of the Form API
  $items['ajax-reader'] = array(
    'page callback' => 'ajax_link_response',
    'access callback' => TRUE,
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
function ajax_link_response($type = 'ajax', $nid = 0){
  drupal_set_message($nid);
  $output = _ajax_reader_load_noder($nid);
  drupal_set_message("hello and output:" . $output);
  drupal_set_message("Hello");

  if ($type == 'ajax') {
    $commands = array();
    $commands[] = ajax_command_replace('#content', '<div id="content">' . $output . '</div>');
    $page = array(
      '#type' => 'ajax',
      '#commands' => $commands
    );
    ajax_deliver($page);
  }
  else{
    $output = '<div id= "content">' . $output . '</div>';
    drupal_set_message("Hello no js");
    return $output;
  }
}
function _ajax_reader_load_noder($nid = 0){
  $node = node_load($nid, NULL, false);
  if ($node){
    $vnode = node_view($node);
    return theme("node", $vnode);
  }
  // return views_embed_view('main_article_page_view', 'default', $nid);
}
